stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/Admission_Prediction.csv
    outs:
    - data/raw/Admission_Prediction.csv

  process_data:
    cmd: python src/EDA.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data/raw/Admission_Prediction.csv
    outs:
    - data/raw/Admission_Prediction1.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/Admission_Prediction1.csv
    params:
    - split_data.test_size
    - split_data.random_state
    outs:
    - data/processed/train_Admission.csv
    - data/processed/test_Admission.csv 

  train_and_evaluate:
    cmd: python src/model_build.py --config=params.yaml
    deps:
    - data/processed/train_Admission.csv
    - data/processed/test_Admission.csv 
    - src/model_build.py
    - src/get_data.py
    
    params:
    - estimators.ElasticNet.params.cv
    - estimators.ElasticNet.params.normalize
    metrics:
    - report/scores.json:
        cache: false
    - report/params.json:
        cache: false
    outs:
    - saved_models/model.joblib