base:
  project: AdmissionPrediction-project
  target_col: Chance_of_Admit

data_source:
  s3_source: data_given/Admission_Prediction.csv

load_data:
  raw_dataset_csv: data/raw/Admission_Prediction.csv

process_data:
  raw_dataset_csv: data/raw/Admission_Prediction1.csv

split_data:
  train_path: data/processed/train_Admission.csv
  test_path: data/processed/test_Admission.csv
  test_size: 0.20
  random_state: 90


estimators:
  ElasticNet:
    params:
      cv: 50
      normalize: true

model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: saved_models/model.joblib
